apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsphere-cloud-controller-manager
  namespace: kube-system
  labels:
    app.kubernetes.io/name: vsphere-cpi
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vsphere-cpi
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vsphere-cpi
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: vsphere-cloud-controller-manager
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      priorityClassName: system-cluster-critical
      containers:
        - name: vsphere-cloud-controller-manager
          image: registry.k8s.io/cloud-provider-vsphere/cpi/manager:v1.29.0
          imagePullPolicy: IfNotPresent
          command:
            - /cloud-controller-manager
          args:
            - "--v=2"
            - "--cloud-provider=vsphere"
            - "--cloud-config=/etc/cloud/vsphere.conf"
            - "--leader-elect=true"
            - "--use-service-account-credentials=true"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10258
              scheme: HTTPS
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10258
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: cloud-config
              mountPath: /etc/cloud
              readOnly: true
      volumes:
        - name: cloud-config
          secret:
            secretName: vsphere-cloud-config
            items:
              - key: vsphere.conf
                path: vsphere.conf
